# Generated by Django 5.0.3 on 2024-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.CharField(max_length=64)),
                ('n_employee', models.CharField(max_length=64)),
                ('task', models.ManyToManyField(blank=True, related_name='employee', to='app1.task')),
            ],
        ),
    ]
